### PR TITLE
perf: remove cache from store(iavl)

### PR DESCRIPTION
**Pull request by dudong2**
## Description

- remove iavl cache and iavl cache manager
closes: #581 

## Motivation and context

Unlike cosmos-sdk, lbm-sdk uses fastcache in iavl. According to the benchmarking results, the performance was better when the cache was not used. So I decided to roll back.

## Checklist:

- [ ] I followed the [contributing guidelines](https://github.com/line/lbm-sdk/blob/main/CONTRIBUTING.md) and [code of conduct](https://github.com/line/lbm-sdk/blob/main/CODE_OF_CONDUCT.md).
- [ ] I have added a relevant changelog to `CHANGELOG.md`
- [ ] I have added tests to cover my changes.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated API documentation `client/docs/swagger-ui/swagger.yaml`

### CODE REVIEW

**Comment by zemyblue** [comment]
Please add changelog to `CHANGELOG.md`

**Comment by zemyblue** [comment]
Please remove `freecache` library in `go.mod`.

**Comment by dudong2** [comment]
> Please add changelog to `CHANGELOG.md`

I added it

**Comment by dudong2** [comment]
> Please remove `freecache` library in `go.mod`.

I removed 'freecache' from 'go.mod'

**Pull request closed without merging**
