### PR TITLE
feat: change wasm metrics method

### PR DESCRIPTION
**Pull request by brew0722**
## Description

closes: #357

The metrics method for observing the wasm was the telemetry.
However, telemetry had performance degradation issues.
Change the method to use prometheus directly. In testing, this did not cause any performance degradation.

In addition to telemetry, wasm already had prometheus metrics for observing the cache of the VM internal implementation.
However, the observation method between our need and exist cache metrics is different .
Existing cache metrics are periodic observation by subscription of prometheus collector,
What we want is to happen at a point in time that run.

So add a new structure without refactoring the existing cache metrics.

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

### CODE REVIEW

**Review by whylee259 — APPROVED** [review]
LGTM

**Review by shiki-tak — APPROVED** [review]
LGTM

**Comment by loloicci** [comment]
This looks not a refactor and looks like a changing feature. Isn't it? (this is tagged refactor in the title)

**Comment by brew0722** [comment]
> This looks not a refactor and looks like a changing feature. Isn't it? (this is tagged refactor in the title)

right, changed

**Review by loloicci — APPROVED** [review]
LGTM! Fill the checkboxes in the description next time 🙇

**Pull request merged**
