### PR TITLE
chore: add progress log into x/collection import-genesis

### PR DESCRIPTION
**Pull request by 0Tech**
## Description

This patch would add progress logs into x/collection import.

For now, the import consists of few items in the following order:
- contract
- next class ids
- classes
- next token ids
- balances
- nfts
- parents
- authorizations
- grants
- statistics (burnt)
- statistics (supply)

Hence, the log would be displayed in the same order.

## Motivation and context

The x/collection genesis candidate is very huge, so it would be helpful to have progress reports.

## Checklist:

- [x] I followed the [contributing guidelines](https://github.com/line/lbm-sdk/blob/main/CONTRIBUTING.md) and [code of conduct](https://github.com/line/lbm-sdk/blob/main/CODE_OF_CONDUCT.md).
- [x] I have added a relevant changelog to `CHANGELOG.md`
- [ ] I have added tests to cover my changes.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated API documentation `client/docs/swagger-ui/swagger.yaml`

### CODE REVIEW

**Review by dudong2 — APPROVED** [review]
LGTM

**Comment by zemyblue** [comment]
How is this progress printed?

**Comment by 0Tech** [comment]
> How is this progress printed?

```
...
2023/03/21-15:16:12.373 INF Starting import contract ... module=x/collection
2023/03/21-15:16:12.373 INF Progress: 33% module=x/collection
2023/03/21-15:16:12.373 INF Progress: 66% module=x/collection
2023/03/21-15:16:12.373 INF Done import contract module=x/collection
...
```

**Review by zemyblue — COMMENTED** [review]
Please write to description all progress reporter type and the orders.

**Review by zemyblue — APPROVED** [review]

**Review by loin3 — APPROVED** [review]

**Pull request merged**
