### PR TITLE
feat: apply Ostracon's changes that replace `StakingPower` with `VotingPower` and `VotingPower` with `VotingWeight`.

### PR DESCRIPTION
**Pull request by zemyblue**
## Description

Apply Ostracon's change that replace `StakingPower` with `VotingPower` and `VotingPower` with `VotingWeight`.
https://github.com/line/ostracon/pull/449

Here is a list of changes.
* StakingPower -> VotingPower
* VotingPower -> VotingWeight

## Checklist:

- [x] I followed the [contributing guidelines](https://github.com/line/lbm-sdk/blob/main/CONTRIBUTING.md) and [code of conduct](https://github.com/line/lbm-sdk/blob/main/CODE_OF_CONDUCT.md).
- [x] I have added a relevant changelog to `CHANGELOG.md`
- [ ] I have added tests to cover my changes.
- [ ] I have updated the documentation accordingly.
- [x] I have updated API documentation `client/docs/swagger-ui/swagger.yaml`

### CODE REVIEW

**Review by dudong2 — APPROVED** [review]

**Comment by dudong2** [comment]
The title is weird. How about changing it to `feat: apply Ostracon's changes that replace StakingPower with VotingPower and VotingPower with VotingWeight`?

**Review by torao — APPROVED** [review]

**Comment by zemyblue** [comment]
> The title is weird. How about changing it to `feat: apply Ostracon's changes that replace StakingPower with VotingPower and VotingPower with VotingWeight`?

I don't know what is different. Do you mean removing backquote in title?

**Comment by dudong2** [comment]
> > The title is weird. How about changing it to `feat: apply Ostracon's changes that replace StakingPower with VotingPower and VotingPower with VotingWeight`?
> 
> I don't know what is different. Do you mean removing backquote in title?

`StakingPower with VotingPower` is duplicated.

**Comment by zemyblue** [comment]
> > > The title is weird. How about changing it to `feat: apply Ostracon's changes that replace StakingPower with VotingPower and VotingPower with VotingWeight`?
> > 
> > 
> > I don't know what is different. Do you mean removing backquote in title?
> 
> `StakingPower with VotingPower` is duplicated.

Oh. I understand. Thank you.

**Review by tnasu — APPROVED** [review]
LGTM

**Pull request merged**
